<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="FB_AutoControl" Id="{87637cc0-4cc2-41ff-b4b8-bf7a9ca647be}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_AutoControl EXTENDS AB_baseController
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="control_crane" Id="{080a653f-f4a5-4ea1-9c1e-8ee04d7c2e61}">
      <Declaration><![CDATA[METHOD control_crane
VAR_INPUT
	stInputs	: ST_inputs_analog;
END_VAR
VAR_OUTPUT
	fCylValve	: REAL;
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[fCylValve := 0;]]></ST>
      </Implementation>
    </Method>
  </POU>
</TcPlcObject>